language: java

sudo: false # faster builds

install: true

jdk:
  - openjdk8
  - openjdk11
  - openjdk17

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2'

script:
  - export TZ=Asia/Shanghai
  - travis_wait 30 mvn clean test -e -B -Pcicd -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

after_success:
  - bash <(curl -s https://codecov.io/bash)
